CURR_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
LIBRARY_PATHS += $(CURR_DIR)/peripherals/ $(CURR_DIR)/devices/ $(CURR_DIR)/services/
SOURCE_PATHS += $(CURR_DIR)/peripherals/ $(CURR_DIR)/devices/ $(CURR_DIR)/services/

